services:

  dashboard:
    build: 
      context: ./dashboard
      dockerfile: ./Dashboard.Dockerfile
    command: sh -c 'pnpm run db:migrate && pnpm dev'
    network_mode: host
    environment:
      - BETTER_AUTH_SECRET=changeme
      - BETTER_AUTH_URL=http://localhost:5050
      - DATABASE_URL=postgresql://postgres:postgres@localhost:54320/main
      - MATHOM_RUNTIME=docker
      - MATHOM_RUNTIME_URL=http://localhost:9090
      - NEXT_PUBLIC_MATHOM_RUNTIME_URL=http://localhost:9090
      - HOSTNAME=0.0.0.0
      - MODE=local
      - NEXT_PUBLIC_MODE=local
      - PORT=5050
    volumes:
      - ./dashboard:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      postgres:
        condition: service_healthy


  runtime:
    build:
      context: ./podrift
      dockerfile: Dockerfile
    network_mode: host
    environment:
      - LOG_URL=http://host.docker.internal:5050/api/v1/instances
      - DATABASE_URL=postgresql://postgres:postgres@localhost:54320/main
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  postgres:
    image: postgres:17
    command: '-d 1'
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '54320:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  db_data:
